# Generated by Django 2.2.2 on 2019-06-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_auto_20190629_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrestaurant',
            name='comentarios',
            field=models.TextField(default='deja tu comentario aqui!', max_length=500),
        ),
    ]
