# Generated by Django 2.2.2 on 2019-06-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0003_auto_20190629_0924'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrestaurant',
            name='categoria',
            field=models.CharField(choices=[('norte_america', 'Norte America'), ('sur_america', 'Sur America'), ('europa', 'Europa'), ('asia', 'Asia'), ('africa', 'Africa'), ('oceania', 'Oceania')], default='sur_america', max_length=50),
        ),
    ]
