# Generated by Django 2.2.2 on 2019-06-29 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0005_auto_20190629_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrestaurant',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
