# Generated by Django 2.2.2 on 2019-06-29 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0006_auto_20190629_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrestaurant',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blog_restaurante', to=settings.AUTH_USER_MODEL),
        ),
    ]
