# Generated by Django 2.2.2 on 2019-06-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0008_postrestaurant_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrestaurant',
            name='categoria',
            field=models.CharField(choices=[('norte america', 'Norte America'), ('sur america', 'Sur America'), ('europa', 'Europa'), ('asia', 'Asia'), ('africa', 'Africa'), ('oceania', 'Oceania')], default='sur america', max_length=50),
        ),
        migrations.AlterField(
            model_name='postrestaurant',
            name='tags',
            field=models.CharField(blank=True, default='Tag', max_length=100, null=True),
        ),
    ]
