# Generated by Django 2.2.2 on 2019-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0009_auto_20190630_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrestaurant',
            name='fecha_edicion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postrestaurant',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postrestaurant',
            name='tags',
            field=models.CharField(blank=True, default='tag', max_length=100, null=True),
        ),
    ]
