# Generated by Django 2.2.2 on 2019-06-30 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0010_auto_20190630_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postrestaurant',
            name='fecha_publicado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
