# Generated by Django 2.2.2 on 2019-06-30 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0011_auto_20190630_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='postrestaurant',
            name='fecha_desactivado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
