# Generated by Django 2.2.2 on 2019-07-01 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0016_auto_20190630_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='comentarios',
            field=models.TextField(default='deja tu comentario aqui!', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='fecha_comentario',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='post_restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurante.PostRestaurant'),
        ),
    ]
